### ISSUE TITLE
make isPickerVisible a two-way binding

### ISSUE THREAD

**Issue by james-criscuolo** [outbrain/pure-angular-date-range-picker#10]
Hi,
  I have a text box in which I can enter the date above the calendar, but as I focus on this input, I can not make the ob-daterangepicker visible as well. There are better ways to deal with this, but I've been able to get around the problem by adding isPickerVisible to the directive's scope definition with `=?` and setting this within `click` or `focus` listeners for the input (hiding seems to work without manually setting it).

  Is this a change you'd be willing to accept? There are certainly better ways to approach my problem, but this is the simplest, quickest solution I could think of. The task of implementing the text box within the project would be best, but that would also be a considerable amount of work, so I was curious if this was acceptable into the project.

Thanks,
James

**Comment by vlio20** [comment]
Can you please provide some example I can see (plunker/codepan)?

Thanks

**Comment by james-criscuolo** [comment]
Sorry for the long delay here, here's a plunkr: http://plnkr.co/edit/8rMpP95hAS5LNVx3Ao2D?p=preview

I have the distributable file with my change uncommented, but you can flip to the clean dist right above it, which won't work (given, there's no code to make it attempt to).

I saw another issue regarding the `api` argument, that may be of some help, so I'm going to look into that.

**Comment by james-criscuolo** [comment]
At a glance, adding `togglePicker` to the `api` option would also solve this, probably in a more preferable way.

**Comment by vlio20** [comment]
Yes I think that it is a better solution to do it via the api.
Please add some tests to it and I will be happy to merge your PR.

Thanks a lot!
