### ISSUE TITLE
Problem with unicode characters

### ISSUE THREAD

**Issue by RickyCampos** [outbrain/pure-angular-date-range-picker#12]
First of all, thanks for the work.
I have a problem with this date range picker when i use OSX and some linux distros. 
The unicode characters of the arrows (◀  and ▶ )  are not displayed correctly because they are not available in these operating systems.
Could you replace this characters by svg icons or something like that?

Thanks, regards
![captura de pantalla 2016-07-07 a las 10 06 10](https://cloud.githubusercontent.com/assets/9297012/16646461/822e0fee-442a-11e6-8938-aba90768cee8.png)

**Comment by vlio20** [comment]
Good point @RickyCampos , I don't want to use images or svgs. 
I probably will fix by replacing it with a css solution (triangle)

**Comment by vlio20** [comment]
@RickyCampos, take a look at the 0.7.0 release.

**Comment by RickyCampos** [comment]
Your Welcome.
Thanks for your work.
