### ISSUE TITLE
Auto open date range picker

### ISSUE THREAD

**Issue by ravishs** [outbrain/pure-angular-date-range-picker#13]
Is there any directive to do this?

**Comment by vlio20** [comment]
I am not sure what you are asking for. Please elaborate.

**Comment by ravishs** [comment]
Hello :)

Was wondering if I could open the date range picker programmatically or
display it inline... Thanks for ur time :)

**Comment by vlio20** [comment]
There is a way to do it with the api object, I will add it to the documentation.
Meanwhile you can take a look at this PR: https://github.com/outbrain/pure-angular-date-range-picker/pull/11

**Comment by vlio20** [comment]
take a look at the [0.7.0](https://github.com/outbrain/pure-angular-date-range-picker/releases/tag/0.7.0) release

**Comment by ravishs** [comment]
Thank you so much :)

Regards,
Ravish

**Comment by vlio20** [comment]
starring the repo will be appreciated :)

**Comment by ravishs** [comment]
Already did 👍
