### ISSUE TITLE
When picking a date range, the 'end' day is exclusive

### ISSUE THREAD

**Issue by aditechsee** [outbrain/pure-angular-date-range-picker#16]
Is there a way to define that 'end' is inclusive?

**Comment by vlio20** [comment]
Hi @aditechsee,
I can't reproduce it, here is screenshot:
http://prntscr.com/c1xdcv

please supply an example + steps to reproduce.

**Comment by aditechsee** [comment]
Hi,
The flow is as follows:
Select a custom date range, for example 01/08 - 07/08
I'd expect to see results from the start of 01/08 until the end of 07/08, but it practice the range that is recieved is start of 01/08 until the end of 06/08, meaning that the last selected date is not included in the range

**Comment by aditechsee** [comment]
Here is my code:
<ob-daterangepicker calendars-always-on="true" on-apply="controller.updateData(start, end)" auto-apply="true"></ob-daterangepicker>

updateData(start, end) {
        console.log(start.toISOString());
        console.log(end.toISOString());
}

Screenshots attached. Note that the dates appear with time of 21:00 because of my TZ is UTC+3, but anyhow you can see I selected 07/08 but the end points to end of 06/08 (meaning it not includes 07/08)
![screenshot from 2016-08-07 12 20 34](https://cloud.githubusercontent.com/assets/19682008/17461544/826d65f4-5c99-11e6-83d6-6eb820541810.png)
![screenshot from 2016-08-07 12 19 21](https://cloud.githubusercontent.com/assets/19682008/17461543/826a763c-5c99-11e6-88d3-940abd38ae52.png)

**Comment by vlio20** [comment]
I can see that both start and end dates are both shifted by when day back. Maybe it is something related to your timezone. 
Currently the calendar is using the client timezone. It would be nice if you will try to run it on the demo page. See if this issue reproduced: http://outbrain.github.io/pure-angular-date-range-picker/

**Comment by aditechsee** [comment]
The shift is not an issue. If we are @ UTC, there would be no shift but still since I select start to be 01/08 and end to be 07/08, I get start = 01/08 (which is right) and end = 06/08 (which is wrong)

**Comment by vlio20** [comment]
thats not what I see in your screenshot (https://cloud.githubusercontent.com/assets/19682008/17461544/826d65f4-5c99-11e6-83d6-6eb820541810.png). Booth start & end are shifted. Is the result 2016-07-31 :: 2016-08-06 while you have selected 2016-08-01 :: 2016-08-07.

**Comment by aditechsee** [comment]
![screenshot from 2016-08-07 13 22 29](https://cloud.githubusercontent.com/assets/19682008/17461838/3a6fd8fa-5ca2-11e6-8f68-89d5b5c51fcb.png)

Attached a screenshot with no shift. Still I requested 01/08 - 07/08, and you can see that the end is 07/08 00:00:00, which means this is the start of the day, not its end

**Comment by aditechsee** [comment]
![screenshot from 2016-08-07 13 22 29](https://cloud.githubusercontent.com/assets/19682008/17461884/34fdd59c-5ca3-11e6-88d2-513c31af06be.png)

Attached a screenshot with no shift. Still I requested 01/08 - 07/08, and you can see that the end is 07/08 00:00:00, which means this is the start of the day, not its end

**Comment by vlio20** [comment]
Very odd, try to reproduce it on the demo.

**Comment by aditechsee** [comment]
Reproduced, see attached. The selected range is 02/08 - 07/08
The console log (coming from the lib code) prints the start and end which clearly shows 07/08 is not included

**Comment by vlio20** [comment]
@aditechsee, please see my screenshot:  
http://prntscr.com/c2obxk

Please provide one like this.

**Comment by vlio20** [comment]
According to you screenshot all the dates are aligned : http://prntscr.com/c2piwy
Please add a screenshot if the date picker opened as well.

Here me putting your dates:
1. http://prntscr.com/c2pjrb
2. http://prntscr.com/c2pjzo

**Comment by aditechsee** [comment]
Your screenshot is identical to mine. My point is when I select end date = 08/08, there are 2 options: inclusive or exclusive. Inclusive means that the end should be set to 08/08 23:59:00 or 09/08 00:00:00
Exclusive means that the end is set to 08/08 00:00:00, which is what we get. My question is is there a way to define end to be inclusive?

**Comment by vlio20** [comment]
Nope. 
I thought that exclusive is not including the selected day. 

PR would be awesome. 

Thanks for the issue.
