### ISSUE TITLE
Can't navigate back through months on day picker with invalid date.

### ISSUE THREAD

**Issue by davidnknight** [outbrain/pure-angular-date-range-picker#17]
Hi!

If you check your own demo http://outbrain.github.io/pure-angular-date-range-picker/, set disabled to false and you're presented with an invalid date, as shown below.

![screen shot 2016-08-25 at 10 28 16](https://cloud.githubusercontent.com/assets/1526840/17963695/b220bfd0-6aae-11e6-841e-58c8ae78b7d8.png)

If you then click the day picker to choose a date and navigate to September, or any future month for that matter, you're unable to navigate back to a previous month, as shown below. Notice that there's only a navigational arrow to go forward through months, not back.

![screen shot 2016-08-25 at 10 24 36](https://cloud.githubusercontent.com/assets/1526840/17963734/d89d5948-6aae-11e6-997b-000c8e3b58f4.png)

Once you've selected a correct date, all seems to work fine with both forward and back arrows to correctly navigate through months, so it seems that it's a bug when starting with an invalid date.

**Comment by vlio20** [comment]
@davidnknight, that you for your contribution.
The bug was fixed in the latest release (0.8.2).

You can check the code in the following commit d52ccd1ff6ae1e146f203dfe7c79f1194aa2bb85
