### ISSUE TITLE
Using Angular Material

### ISSUE THREAD

**Issue by stevezau** [outbrain/pure-angular-date-range-picker#2]
Hi,

This was the only date range picker in pure angular that i could find, so thanks for releasing this!

I am using it at the moment but the design and layout could do with some improvements, have you thought about supporting the Angular Material design directives?

**Comment by stevezau** [comment]
PS: I'm happy to help, just dont want to double up on work if you are already on it.

**Comment by vlio20** [comment]
hi @stevezau,
I think it is a good idea to be able to add themes to the picker, but there are a lot of features that I would like to implement before that. It would be great if you can do a pull request and supply some Material theme (without the angular material or any other 3rd party lib - in order to keep the repo as light as possible). Keep in mind that it should be optional.

**Comment by stevezau** [comment]
@vlio20 ok, i'll take a look.

Before I jump in did you have any idea how you would like the theme picker to work?

**Comment by vlio20** [comment]
@staslev, you talking about css tweaks, no functionality, right?
If so then the most simple approach is to add a class to the directive (for example: material) and that will change the theme to material. Do you have other Ideas?

**Comment by stevezau** [comment]
@vlio20 I don't it's that simple. Angular Material (https://material.angularjs.org/latest/) has a bunch directives directives for things like select, input etc. This would require changes to the html files.

**Comment by vlio20** [comment]
@stevezau, I see but then it will require using the angular material module - and its something I don't want to do. Maybe using material lite (http://www.getmdl.io/index.html) will help, WDYT?

**Comment by stevezau** [comment]
@vlio20, yeah it will require angular material which seems fast becoming a standard for angular apps.

I've had a look at MDL previously but chose not to bother as Angular Material provides much more value. Either way I will be adding a theme for your daterange picker in angular material style. Maybe we can include it as a plugin instead?

**Comment by vlio20** [comment]
@stevezau, How do you think to implement this? Maybe you can bring some mocks of how this component should look like materialized.

**Comment by mominsamir** [comment]
http://mominsamir.github.io/date-time-picker/#/range-picker-demo

Check this if it helps

**Comment by vlio20** [comment]
@mominsamir, nice! I will close this issue.
