### ISSUE TITLE
Wrong weekday names when using moment.js with locale.js file

### ISSUE THREAD

**Issue by Jean-Rashmir** [outbrain/pure-angular-date-range-picker#20]
When moment.js is used with a language/locale file (for example "de-at.js") the weekdays in the calendar grid are wrong for some months. 

I have created a plunkr that illustrates the issue: [https://plnkr.co/edit/l0CzItjuNmqCp4uICkwO?p=preview](https://plnkr.co/edit/l0CzItjuNmqCp4uICkwO?p=preview)

If the "locale".js file is removed all weekday names are displayed as expected.

**Comment by vlio20** [comment]
@Jean-Rashmir , thanks for opening an issue. I will look at it in the next few days.

**Comment by vlio20** [comment]
@Jean-Rashmir , Issue was resolved in 0.8.2 version.
Thanks for your contribution,
