### ISSUE TITLE
directive bindings should not be function

### ISSUE THREAD

**Issue by pdemilly** [outbrain/pure-angular-date-range-picker#24]
Why are most of obDateRangePicker bindings, functions?

scope: {
      weekStart: '&',
      range: '=?',
      weekDaysName: '&',
      format: '&',
      ranges: '&',
      minDay: '&',
      maxDay: '&',
      monthFormat: '&',
      inputFormat: '&',
      onApply: '&',
      linkedCalendars: '&',
      autoApply: '&',
      disabled: '&',
      calendarsAlwaysOn: '&',
      api: '=?'
    },

**Comment by vlio20** [comment]
@pdemilly, its how you do one way data binding in angular 1 (from within the directive). This are basically getters. 
Does this causes any problem?

**Comment by pdemilly** [comment]
I am trying to get it work. In particular calendars-always-on which to me would imply that the calendars widget is always displayed beneath the date selector. It is not working for me. I tried to follow your directive hence my question.

**Comment by vlio20** [comment]
@pdemilly, can you share your code (plunker, codepen)?

**Comment by pdemilly** [comment]
It's a little complicated as I am using it inside handsontable. But on your example page you can see that calendars-always-on: true doesn't open the calendar.

If your directive I can see ng-show="obDateRangePicker.isCustomVisible" but that variable is not updated regardless of what value you set calendars-always-on to.

**Comment by pdemilly** [comment]
Also by the way you should look at component which support 1 way binding. Finally an easier way to deal with minimum watchers would be to just pass an range-picker-options map and just watch it or not

**Comment by vlio20** [comment]
it seems like there is an issue with the demo (I will fix it), but the calendars always  on property is showing or hiding the calendars (not the entire picker). http://prntscr.com/d378y9

**Comment by vlio20** [comment]
@pdemilly, the demo is fixed in 0.9.4 version (you can see it already in the demo page: http://outbrain.github.io/pure-angular-date-range-picker/).
