### ISSUE TITLE
Uminified

### ISSUE THREAD

**Issue by michelem09** [outbrain/pure-angular-date-range-picker#25]
You should provide also an unminified version of it.

**Comment by vlio20** [comment]
@michelem09 , thanks for opening an issue - check out 0.10.0 version.
dist/scripts/min/ob-daterangepicker.js is now only concatenated.

**Comment by michelem09** [comment]
Thanks, could I ask you to provide also the CSS unminified?
I'm asking this because usually I work with bower and grunt and I let grunt to do all the minify operations for the production env while I can work in dev with uminified files (that's better if you have a problem or if you need to modify something).
