### ISSUE TITLE
Cancel does not clear ng-model value

### ISSUE THREAD

**Issue by w-A-L-L-e** [outbrain/pure-angular-date-range-picker#26]
The cancel actually is broken it does not return to initial state.
For instance you take a custom selection then click cancel when you then re-open it goes back to the full view with the ranges without only the dropdown. Also cancel should make the assigned ng-model var be empty like on initial page load. Right now cancel button only closes the dropdown but keeps the ng-model var to the previous selected value.

**Comment by vlio20** [comment]
@w-A-L-L-e , It is by design keeps the previous value if you click cancel. 
There should be a clear button added to the dropdown I am just not sure what would be the best UI. Please follow this issue here: #18
