### ISSUE TITLE
calendars-always-on

### ISSUE THREAD

**Issue by daveconger** [outbrain/pure-angular-date-range-picker#28]
I might suggest making this true by default.  It seems like this would normally be the case.  But more importantly, I thought your component was broken when I first installed it and I spent extra time searching for other date range pickers when this was the one I really wanted.  Following the usage guidelines, writing just `<ob-daterangepicker range="vm.range"></ob-daterangepicker>` results in a mostly empty white box dropping down.  I see now that this box holds the custom ranges, but that wasn't immediately clear.

Alternatively, I suppose the documentation could be changed to make this more obvious up front.

Thanks for your excellent work!

**Comment by vlio20** [comment]
Hi @daveconger,
I don't see any reason not to follow your suggestion.
Here is the link to the documentation states that the default behaviour is calendars-always-on="false":
https://github.com/outbrain/pure-angular-date-range-picker#calendars-always-on.

I will close this issue for now, though PR would be nice.
