### ISSUE TITLE
Uncaught exception using api

### ISSUE THREAD

**Issue by daveconger** [outbrain/pure-angular-date-range-picker#29]
I'm getting an uncaught exception on line 1222 with "this.pickerApi.setCalendarPosition is not a function" when trying to use the setDateRange method.  If I continue, it appears to take anyway.

I'm trying to force set date range on page load.  The problem is that the data is coming via a promise, and angular seems to miss it on the digest.  So I'm calling setDateRange in the promise callback, which works except for the above error.  It looks like maybe the api isn't fully initialized until I click on the component, even though the setDateRange method is defined.  Does this make sense?

**Comment by vlio20** [comment]
@daveconger, can you create some plunker?
