### ISSUE TITLE
can't use api parameter

### ISSUE THREAD

**Issue by DeerBeer** [outbrain/pure-angular-date-range-picker#32]
Hi, I'm using this component for filters and it suites our need. But there was request to reset datepicker value to some of predefined, so I needed to refresh picker selected value. I have setup api parameter and called setDateRange, but it always writes error in console because pickerApi is empty. I don't see how to pass  function or some other parameter to internal pickerApi object.

**Comment by vlio20** [comment]
Why just not to change the range object to the date you need? this automatically will select the corresponding predefined range.

**Comment by DeerBeer** [comment]
I have done that but something is missing.
I have set this for range: range="filter.value"
and in code I have when I want to change:
`                        filter.value.start = moment().subtract(120, 'months').startOf('day');
                        filter.value.end = moment().endOf('day');
`

And it is not changing the value

**Comment by vlio20** [comment]
what are the predefined time ranges that you have?

**Comment by DeerBeer** [comment]
scope.dateRanges = [
          {
             name: '',
             start: moment().subtract(120, 'months').startOf('day'),
             end: moment().endOf('day')
         },
        {
            name: 'Last Month',
            start: moment().subtract(1, 'months').startOf('day'),
            end: moment().endOf('day')
        },
        {
            name: 'Last 3 Months',
            start: moment().subtract(3, 'months').startOf('day'),
            end: moment().endOf('day')
        },
        {
            name: 'Last 6 Months',
            start: moment().subtract(6, 'months').startOf('day'),
            end: moment().endOf('day')
        },
        {
            name: 'Last Year',
            start: moment().subtract(1, 'years').startOf('day'),
            end: moment().endOf('day')
        }
        ];

**Comment by vlio20** [comment]
I have created this plunker:  
https://plnkr.co/edit/wGMs4pjBBg4rXNYWaIaE?p=preview

It seems like a bug. Will take a look ASAP.

Thanks for opening an issue.

**Comment by DeerBeer** [comment]
Thanks

**Comment by vlio20** [comment]
@DeerBeer, please try to use version 0.10.2. 
Also please take a look at the following example on how to set the range you want via api:
https://plnkr.co/edit/2adO8ZrFMxdAo9Ex0s7F?p=preview

```
vm.setSpecificRange = function() {
    vm.api.setDateRange({
      start: moment().subtract(120, 'months').startOf('day'),
      end: moment().endOf('day')
    });
 }
```

If fixed please confirm and close.

**Comment by DeerBeer** [comment]
Everything works now perfectly , thanks for your quick response and solution.

**Comment by vlio20** [comment]
@DeerBeer, you welcome! a star would be nice :)

**Comment by DeerBeer** [comment]
There it is, a new start on your sky :)
