### ISSUE TITLE
start.isSame is not a function

### ISSUE THREAD

**Issue by olegdemkovych** [outbrain/pure-angular-date-range-picker#33]
How to set **All** or **None** option to ranges?

```
{
    name: 'All',
    start: 'undefined',
    end:  'undefined'
}
```

or 

```
{
    name: 'All',
    start: null,
    end:  null
}
```
doesn't work.

**Comment by vlio20** [comment]
Currently there is no way to not select any date range, regarding "all" I am not sure what does it mean. Can you please elaborate?

**Comment by olegdemkovych** [comment]
Ok, will try
