### ISSUE TITLE
Thoughts/Plans on Angular version >= 2?

### ISSUE THREAD

**Issue by james-criscuolo** [outbrain/pure-angular-date-range-picker#34]
I've been part of converting my company's application off of AngularJS, and on to Angular. It's a large undertaking to convert pieces to Angular, so I know this is no small "issue" (more of a feature request really), but there are really no Angular 2+ daterangepickers that match the functionality of this one, while still not using bootstrap or jquery.

I have no interest in maintaining a repo for this going forward, but I would be glad to assist in the conversion if it would be something the authors are interested. In the meantime, I may explore wrapping this so it is angular2-capable, which looks like what some people are doing with the major jquery daterangepicker out there.

**Comment by vlio20** [comment]
@james-criscuolo, there are no plans currently to upgrade this repo to Angular. Though there are thoughts of doing this in the angular-datepicker repo, here is a link: https://github.com/vlio20/angular-datepicker. This datepicker has many features which should make the creation of daterange picker easier then starting from scratch. 
Maybe in the future we will make the required changes to support Angular in this repor. 

It whould be supper cool if you will list the features you are using with this component.

**Comment by james-criscuolo** [comment]
I hadn't found that one! All of my searches had been involving "angular 2" because I know most angularjs libraries still go just by the "angular" name, since the change in naming convention occurred so late. I should've thought to check your repos though.

Anyways, I'll definitely give that a look. I figured it wouldn't be in the same repo. I'll close this issue and open anything that occurs with the new picker over on that repo.

Thanks again!
