### ISSUE TITLE
Default font $mainFont

### ISSUE THREAD

**Issue by daveconger** [outbrain/pure-angular-date-range-picker#35]
Is there a reason you're setting a default font?  I changed the css to inherit the font, which seems to make more sense in general but maybe I'm missing something.  At any rate, Open Sans doesn't seem to be very common so the default on my machine is Times New Roman -- not a good look.

**Comment by vlio20** [comment]
@daveconger, you are probably right. Will fix it in the next release.
Thanks!

**Comment by vlio20** [comment]
@daveconger, this was fixed by @dwido in 0.10.4.

Thanks for the contribution.
