### ISSUE TITLE
Multiple "Custom" label in the ranges list

### ISSUE THREAD

**Issue by wonsikin** [outbrain/pure-angular-date-range-picker#37]
There are many "Custom" label appear in the ranges list when configuring  via the `dateRangePickerConfProvider`

![image](https://cloud.githubusercontent.com/assets/6659426/26137586/bd31373e-3af5-11e7-9395-d3aa3643119c.png)

I have many page use the date range picker. When I choose a custom date range in one page, then i jump into another page, I will see a new custom label shown in the ranges list.

**Comment by vlio20** [comment]
@wonsikin, thanks for opening the issue.
I think I know why this is happening and I will try to solve this ASAP within the component. 
Meanwhile I suggest to to create new reference for the ranges array which is passed to the component, try to do something like that:
``` javascript
ranges = [].concat.ranges;
```

**Comment by wonsikin** [comment]
@vlio20 Thanks

**Comment by vlio20** [comment]
@wonsikin , did the workaround work?

**Comment by wonsikin** [comment]
@vlio20 It works

**Comment by vlio20** [comment]
Glad to hear
