### ISSUE TITLE
Datepicker breaks when clicking multiple times

### ISSUE THREAD

**Issue by ionutanin** [outbrain/pure-angular-date-range-picker#41]
I've updated daterange and got 0.10.5 and I noticed there is an animation implemented for dropdown by class name, the animation takes about 300ms, I don't know exactly, but if I click between this range twice, the dropdown breaks. I went back to 0.10.1 meanwhile, functional version.

LE: is fully functional on 0.11.0, I  will leave the comment for others to find just in case.

P.S. thanks for building this. very nice and pretty :) 👍

**Comment by vlio20** [comment]
Please see if 0.11.0 fixes your issue.

**Comment by ionutanin** [comment]
yes, 0.11.0 fixes the issue
