### ISSUE TITLE
Date ranges are crippled when entering dates in the past

### ISSUE THREAD

**Issue by chubbard** [outbrain/pure-angular-date-range-picker#45]
From my last pull request that was merged some UX problems were introduced that moved calendars back to todays date after the user selected their first date of the range.  This caused serious issues when entering date ranges in the past.  It's pretty much unusable.  Fortunately I fixed it and I'm submitting a pull request for it.  I know the library is in maintenance mode, but I figured this needed to be fixed.

**Comment by vlio20** [comment]
Hi @chubbard this repo is no longer maintained.
