### ISSUE TITLE
Installing through NPM

### ISSUE THREAD

**Issue by james-criscuolo** [outbrain/pure-angular-date-range-picker#6]
Hi,
  When I install through npm, I get a dependency on "babel-plugin-object-assign," which makes sense because of the package.json. This then goes on to install babel-core, which is pretty large.

I don't really know babel, but considering these things don't seem to install through bower, are they necessary if I'm looking to install and use this (as in, not build it, just use the dist folder)? If not, I think just moving the babel-plugin-object-assign to a dev-dependency would probably fix this, along with adding the bower dependencies (moment and angular) to the actual dependencies.

I could put a pull request together if the above makes sense, but I wanted to make sure I wasn't missing something obvious, since I am not familiar with babel.

Thanks,
James

**Comment by vlio20** [comment]
You are right. It should be a dev dependency. Pull request would be nice. Thanks.

**Comment by vlio20** [comment]
Thanks @james-criscuolo

**Comment by james-criscuolo** [comment]
Thanks for the speedy replies and merge! Any chance of a version bump for this now?

**Comment by vlio20** [comment]
I want to do version bump after resolving #5, I hope it will be today.

**Comment by vlio20** [comment]
@james-criscuolo, checkout 0.5.0 version.

**Comment by james-criscuolo** [comment]
great, thank you!
