### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by studel** [outbrain/pure-angular-date-range-picker#8]
Hi,

I use your component in a multilingual context and it seems "week-days-name" and "ranges" attributes are not binding. So is not possible to change range picker language without page reload.

Is there a callback function to force reload of unbinds attributes ?

**Comment by vlio20** [comment]
yes, you can provide an object to api attribute. like so:

` api="range.dateRangeApi"`

range - your controller name.
`dateRangeApi` - should be an object (`dateRangeApi = {}`)

a render method will be set on this `dateRangeApi` object, when required just call `dateRangeApi.render()`.

You can see a full working example here: 
https://github.com/outbrain/pure-angular-date-range-picker/blob/master/src/index.html#L161

Let me know if it solved your issue.

**Comment by studel** [comment]
I used this function but it sometimes generates a javascript error. I no longer use it for that reason.

vendor.js:15715 TypeError: o.pickerApi.render is not a function
    at Object.api.s.render (ob-daterangepicker.js:816)
    at RangeCtrl.render ((index):100)
    at fn (eval at <anonymous> (vendor.js:16560), <anonymous>:4:369)
    at i (vendor.js:26808)
    at p.$eval (vendor.js:19247)
    at p.$apply (vendor.js:19347)
    at HTMLInputElement.<anonymous> (vendor.js:26813)
    at zt (vendor.js:6541)
    at HTMLInputElement.Bt.n (vendor.js:6529)

You can see an exemple on your demo page :
http://outbrain.github.io/pure-angular-date-range-picker/
enter a "Max day" value and validate with enter key.

**Comment by vlio20** [comment]
I can't see any error, take a look: http://prntscr.com/b7jerw (no errors in the console)
